/*
 * generated by Xtext 2.9.1
 */
package net.mydreamy.requirementmodel.springboot

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor


/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class REMODELUiModule extends AbstractREMODELUiModule {
}
