/*
 * generated by Xtext 2.15.0
 */
package net.mydreamy.requirementmodel.springboot;

import com.google.inject.Injector;

import net.mydreamy.requirementmodel.springboot.internal.RequirementmodelActivator;

import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class REMODELExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RequirementmodelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RequirementmodelActivator activator = RequirementmodelActivator.getInstance();
		return activator != null ? activator.getInjector(RequirementmodelActivator.NET_MYDREAMY_REQUIREMENTMODEL_REMODEL) : null;
	}

}
